import type { Metadata } from "next";
import { Inter, Montserrat, Yeon_Sung } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-inter",
});

const sung = Yeon_Sung({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-sung",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.variable} ${inter.variable} ${sung.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
